spring.application.name=FinEdgeAPI

# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/finedge_db
spring.datasource.username=root
spring.datasource.password=Lucifer@54321

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# SERVER
# ===============================
server.port=8080
# ===============================
# JWT CONFIGURATION
# ===============================
jwt.secret=ThisIsASecretKeyForFinEdgeApplication2026SecureKey12345
jwt.expiration=86400000